export const calculatorButtons = [
	{ val: 7, operator: false },
	{ val: 8, operator: false },
	{ val: 9, operator: false },
	{ val: "/", operator: true },
	{ val: 4, operator: false },
	{ val: 5, operator: false },
	{ val: 6, operator: false },
	{ val: "*", operator: true },
	{ val: 1, operator: false },
	{ val: 2, operator: false },
	{ val: 3, operator: false },
	{ val: "-", operator: true },
	{ val: "", operator: false },
	{ val: 0, operator: false },
	{ val: ".", operator: false },
	{ val: "+", operator: true },
];
